apiVersion: apps/v1
kind: Deployment
metadata:

  name: cart
  namespace: roboshop
  labels:
    tier: app
    project: roboshop
    env: dev

spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
      project: roboshop
      env: dev

  template:
    metadata:
      labels:
        tier: app
        project: roboshop
        env: dev

    spec:
      containers:
      - name: cart
        image: surajk879/cart:1.3
        envFrom:
        - configMapRef:
            name: cart

---

apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop

spec:
  selector:
    tier: app
    project: roboshop
    env: dev

  ports:
    - name: cart-port
      protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop

data:
  REDIS_HOST: redis
  CATALOGUE_HOST: catalogue
  CATALOGUE_PORT: 8080

