# DEPLOYEMNT FILE

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    tier: db
    project: roboshop
    env: dev

spec:
  replicas: 1
  selector:
    matchLabels:
      tier: db
      env: dev

  template:
    metadata:
      labels:
        tier: db
        env: dev
    spec:
      containers:
      - name: mongodb
        image: surajk879/mongodb:1.5 

# Service file

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop

spec:
  selector:
      tier: db
      project: roboshop
      env: dev
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 27017
    targetPort: 27017


