apiVersion: apps/v1
kind: Deployment
metadata:
  
  name: mongodb
  namespace: roboshop # declaring namespace
  labels:   # these labels belongs to deployment
    tier: db
    project: roboshop
    env: dev

spec:
  replicas: 1
  selector:
    matchLabels: # these labels should match with pod
      tier: db
      project: roboshop
      env: dev

  template:
    metadata: # this is pod definition
      labels:
        tier: db
        project: roboshop
        env: dev

    spec:
      containers:
      - name: mongodb
        image: surajk879/mongodb:1.3


# defining service to establish communication in between pods

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop

spec:
  selector: # labels should be match with pod
    tier: db
    project: roboshop
    env: dev

  ports:
    - name: mongodb-port
      protocol: TCP
      port: 27017 # port belongs to service
      targetPort: 27017 # port belongs to container







