apiVersion: apps/v1
kind: Deployement
metadata:
  
  name: mongodb
  namespace: roboshop # declaring namespace
  labels:   # these labels belongs to deployment
    tier: db
    project: roboshop
    env: dev

spec:
  replicas: 1
  selector:
    matchLabels: # these labels should match with pod
      tier: db
      project: roboshop
      env: dev

  template:
    metadata: # this is pod definition
      labels:
        tier: db
        project: roboshop
        env: dev

    spec:
      containers:
      - name: mongodb
        image: surajk879/mongodb:1.3


# defining service to establish communication in between pods






