apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    tier: db
    project: roboshop
    env: dev

spec:
  replicas: 1
  selector:
    matchLabels:
      tier: db
      project: roboshop
      env: dev

  template:
    metadata:
      labels:
        tier: db
        project: roboshop
        env: dev

    spec:
      containers:
      - name: mysql
        image: surajk879/mysql:1.3
        envFrom:
        - configMapRef:
            name: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop

spec:
  selector:
    tier: db
    project: roboshop
    env: dev
  
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop

data:
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes" 
    MYSQL_DATABASE: "cities" 
    MYSQL_USER: "shipping" 
    MYSQL_PASSWORD: "RoboShop@1"
