# DEPLOYEMNT FILE

apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    tier: db
    project: roboshop
    env: dev

spec:
  replicas: 1
  selector:
    matchLabels:
      tier: db
      env: dev

  template:
    metadata:
      labels:
        tier: db
        env: dev
    spec:
      containers:
      - name: catalogue
        image: surajk879/catalogue:1.5 
        envFrom:
        - configMapRef:
            name: catalogue-config

# Service file

---

apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop

spec:
  selector:
      tier: db
      project: roboshop
      env: dev
  ports:
  - name: catalogue-port
    protocol: TCP
    port: 8080
    targetPort: 8080

# Config Map file

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-config
  namespace: roboshop

data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
