apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    tier: app
    project: roboshop
    env: dev

spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
      project: roboshop
      env: dev

  template:
    metadata:
      labels:
        tier: app
        project: roboshop
        env: dev

    spec:
      containers:
      - name: user
        image: surajk879/user:1.5
        envFrom:
        - configMapRef:
            name: user
        

---

apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop

spec:
  selectors:  
    tier: app
    project: roboshop
    env: dev
  ports:
  - name: user
    protocol: TCP
    port: 8080
    targetPort: 8080

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop

data:
  MONGO: "true"
  REDIS_HOST: "redis"
  MONGO_URL: "mongodb://mongodb:27017/users"

