apiVersion: v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels:
    tier: db
    project: roboshop
    env: dev

spec:
  replicas: 1
  selector:
    tier: db
    project: roboshop
    env: dev

  template:
    metadata:
      labels:
        tier: db
        project: roboshop
        env: dev

    spec:
      containers:
      - name: redis
        image: redis

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop

spec:
  selector:
    tier: db
    project: roboshop
    env: dev

  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379

    